"""baseline -- the 14-table schema as it existed the moment Alembic was
introduced (see AGENTS.md's 1.7 pass narrative). Every workspace that
predates this migration is detected and stamped to exactly this revision
before being upgraded further -- see storage/migrate.py's legacy-workspace
branch. This migration's upgrade() must therefore always exactly match
what Base.metadata.create_all() would have produced before this pass;
never edit it after the fact, only add new migrations on top.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-10 21:16:55.587854

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import gaggle.storage.database

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_index",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_path", sa.String(), nullable=False),
        sa.Column(
            "start_time", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "end_time", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("preservation_state", sa.String(), nullable=False),
        sa.Column("review_decision", sa.String(), nullable=False),
        sa.Column("camera_count", sa.Integer(), nullable=False),
        sa.Column("cameras_csv", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "face_cluster",
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("representative_crops_csv", sa.String(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column(
            "last_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("merged_into", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cluster_id"),
    )
    with op.batch_alter_table("face_cluster", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_face_cluster_merged_into"), ["merged_into"], unique=False
        )

    op.create_table(
        "face_observation",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column(
            "observed_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("crop_path", sa.String(), nullable=False),
        sa.Column("crop_sha256", sa.String(), nullable=False),
        sa.Column("detector_confidence", sa.Float(), nullable=False),
        sa.Column("embedding_distance_to_cluster", sa.Float(), nullable=True),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("detector_version", sa.String(), nullable=False),
        sa.Column("duplicate_of_observation_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("face_observation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_face_observation_clip_id"), ["clip_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_face_observation_cluster_id"), ["cluster_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_face_observation_event_id"), ["event_id"], unique=False
        )

    op.create_table(
        "media_index",
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("stored_path", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column(
            "start_time", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "end_time", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("ingest_mode", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("clip_id"),
    )
    with op.batch_alter_table("media_index", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_index_camera_id"), ["camera_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_index_sha256"), ["sha256"], unique=False)

    op.create_table(
        "merge_suggestion",
        sa.Column("suggestion_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("basis", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "resolved_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("suggestion_id"),
    )
    with op.batch_alter_table("merge_suggestion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merge_suggestion_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_merge_suggestion_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_merge_suggestion_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_merge_suggestion_target_id"), ["target_id"], unique=False
        )

    op.create_table(
        "plate_observation",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column(
            "observed_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("crop_path", sa.String(), nullable=False),
        sa.Column("crop_sha256", sa.String(), nullable=False),
        sa.Column("raw_ocr_text", sa.String(), nullable=False),
        sa.Column("normalized_text", sa.String(), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=False),
        sa.Column("detector_confidence", sa.Float(), nullable=False),
        sa.Column("review_status", sa.String(), nullable=False),
        sa.Column("user_corrected_text", sa.String(), nullable=True),
        sa.Column("detector_version", sa.String(), nullable=False),
        sa.Column("duplicate_of_observation_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("plate_observation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plate_observation_clip_id"), ["clip_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_plate_observation_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plate_observation_normalized_text"), ["normalized_text"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plate_observation_review_status"), ["review_status"], unique=False
        )

    op.create_table(
        "plate_record",
        sa.Column("plate_id", sa.String(), nullable=False),
        sa.Column("normalized_text", sa.String(), nullable=False),
        sa.Column(
            "created_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column(
            "last_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column("example_crops_csv", sa.String(), nullable=False),
        sa.Column("merged_into", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("plate_id"),
    )
    with op.batch_alter_table("plate_record", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plate_record_merged_into"), ["merged_into"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plate_record_normalized_text"), ["normalized_text"], unique=True
        )

    op.create_table(
        "review_action",
        sa.Column("action_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column(
            "timestamp", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("notes", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("action_id"),
    )
    with op.batch_alter_table("review_action", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_action_event_id"), ["event_id"], unique=False)

    op.create_table(
        "triage",
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("signal_count", sa.Integer(), nullable=False),
        sa.Column("event_ids_csv", sa.String(), nullable=False),
        sa.Column(
            "classified_at",
            gaggle.storage.database.UTCDateTimeColumn(timezone=True),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("clip_id"),
    )
    with op.batch_alter_table("triage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_triage_camera_id"), ["camera_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_triage_state"), ["state"], unique=False)

    op.create_table(
        "vehicle_appearance_cluster",
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("representative_crops_csv", sa.String(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column(
            "last_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("merged_into", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cluster_id"),
    )
    with op.batch_alter_table("vehicle_appearance_cluster", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vehicle_appearance_cluster_merged_into"), ["merged_into"], unique=False
        )

    op.create_table(
        "vehicle_appearance_observation",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column(
            "observed_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("crop_path", sa.String(), nullable=False),
        sa.Column("crop_sha256", sa.String(), nullable=False),
        sa.Column("fingerprint_json", sa.String(), nullable=False),
        sa.Column("detector_confidence", sa.Float(), nullable=False),
        sa.Column("embedding_distance_to_cluster", sa.Float(), nullable=True),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("detector_version", sa.String(), nullable=False),
        sa.Column("duplicate_of_observation_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("vehicle_appearance_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vehicle_appearance_observation_clip_id"), ["clip_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vehicle_appearance_observation_cluster_id"), ["cluster_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vehicle_appearance_observation_event_id"), ["event_id"], unique=False
        )

    op.create_table(
        "voice_cluster",
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column(
            "last_seen_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=True
        ),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("merged_into", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cluster_id"),
    )
    with op.batch_alter_table("voice_cluster", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_voice_cluster_merged_into"), ["merged_into"], unique=False
        )

    op.create_table(
        "voice_observation",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("clip_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column(
            "observed_at", gaggle.storage.database.UTCDateTimeColumn(timezone=True), nullable=False
        ),
        sa.Column("segment_start_seconds", sa.Float(), nullable=False),
        sa.Column("segment_end_seconds", sa.Float(), nullable=False),
        sa.Column("voiceprint_json", sa.String(), nullable=False),
        sa.Column("energy_confidence", sa.Float(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("detector_version", sa.String(), nullable=False),
        sa.Column("duplicate_of_observation_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("voice_observation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voice_observation_clip_id"), ["clip_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_voice_observation_cluster_id"), ["cluster_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_voice_observation_event_id"), ["event_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("voice_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_observation_event_id"))
        batch_op.drop_index(batch_op.f("ix_voice_observation_cluster_id"))
        batch_op.drop_index(batch_op.f("ix_voice_observation_clip_id"))

    op.drop_table("voice_observation")
    with op.batch_alter_table("voice_cluster", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_cluster_merged_into"))

    op.drop_table("voice_cluster")
    with op.batch_alter_table("vehicle_appearance_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vehicle_appearance_observation_event_id"))
        batch_op.drop_index(batch_op.f("ix_vehicle_appearance_observation_cluster_id"))
        batch_op.drop_index(batch_op.f("ix_vehicle_appearance_observation_clip_id"))

    op.drop_table("vehicle_appearance_observation")
    with op.batch_alter_table("vehicle_appearance_cluster", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vehicle_appearance_cluster_merged_into"))

    op.drop_table("vehicle_appearance_cluster")
    with op.batch_alter_table("triage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_triage_state"))
        batch_op.drop_index(batch_op.f("ix_triage_camera_id"))

    op.drop_table("triage")
    with op.batch_alter_table("review_action", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_action_event_id"))

    op.drop_table("review_action")
    with op.batch_alter_table("plate_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plate_record_normalized_text"))
        batch_op.drop_index(batch_op.f("ix_plate_record_merged_into"))

    op.drop_table("plate_record")
    with op.batch_alter_table("plate_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plate_observation_review_status"))
        batch_op.drop_index(batch_op.f("ix_plate_observation_normalized_text"))
        batch_op.drop_index(batch_op.f("ix_plate_observation_event_id"))
        batch_op.drop_index(batch_op.f("ix_plate_observation_clip_id"))

    op.drop_table("plate_observation")
    with op.batch_alter_table("merge_suggestion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merge_suggestion_target_id"))
        batch_op.drop_index(batch_op.f("ix_merge_suggestion_status"))
        batch_op.drop_index(batch_op.f("ix_merge_suggestion_source_id"))
        batch_op.drop_index(batch_op.f("ix_merge_suggestion_entity_type"))

    op.drop_table("merge_suggestion")
    with op.batch_alter_table("media_index", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_index_sha256"))
        batch_op.drop_index(batch_op.f("ix_media_index_camera_id"))

    op.drop_table("media_index")
    with op.batch_alter_table("face_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_face_observation_event_id"))
        batch_op.drop_index(batch_op.f("ix_face_observation_cluster_id"))
        batch_op.drop_index(batch_op.f("ix_face_observation_clip_id"))

    op.drop_table("face_observation")
    with op.batch_alter_table("face_cluster", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_face_cluster_merged_into"))

    op.drop_table("face_cluster")
    op.drop_table("event_index")
    # ### end Alembic commands ###
